### ISSUE TITLE
Unused hooks report invalid arguments

### ISSUE THREAD

**Issue by bradobro** [snikch/goodman#11]
## summary

**When** I make a simple hook server with the goodman library...
**I expect** hooks I don't implement to be ignored.
**Instead** I get warnings
**Even though** the hooks I did implement work properly.
### my hook server

``` go
package main

import (
    "fmt"

    "github.com/snikch/goodman/hooks"
    trans "github.com/snikch/goodman/transaction"
)

func main() {
    h := hooks.NewHooks()
    server := hooks.NewServer(h)

    h.BeforeAll(func(t []*trans.Transaction) {
        fmt.Println("THIS IS A DREDD TEST HOOK WRITTEN IN GOLANG BeforeAll starting.")
    })

    server.Serve()
    defer server.Listener.Close()
}
```
### unexpected error messages

```
info: Hook handler stdout: Completed

info: Hook handler stderr: 2016/07/14 11:57:40 Starting hooks server in go routine

info: Hook handler stderr: 2016/07/14 11:57:40 method After reply type not a pointer: hooks.Callback
2016/07/14 11:57:40 method AfterAll has wrong number of ins: 2
2016/07/14 11:57:40 method AfterEach has wrong number of ins: 2
2016/07/14 11:57:40 method Before reply type not a pointer: hooks.Callback
2016/07/14 11:57:40 method BeforeAll has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeEach has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeEachValidation has wrong number of ins: 2
2016/07/14 11:57:40 method BeforeValidation reply type not a pointer: hooks.Callback
```
### Successful portion

```
info: Hook handler stdout: Starting

info: Hook handler stdout: Accepting connection

info: Connected to the hook handler, waiting 0.1s to start testing.
info: Hook handler stdout: THIS IS A DREDD TEST HOOK WRITTEN IN GOLANG BeforeAll starting.

```

**Comment by snikch** [comment]
Urgh, very odd. @ddelnano any ideas on this one?

Are they warnings (and it still passes / exit 0) or are they errors and have a non 0 exit?

**Comment by ddelnano** [comment]
Sorry I've been on vacation. Those warnings are because the struct that is used as an RPC server has some methods that don't match the function signature that methods available via RPC need to be.  I was thinking about splitting those methods out of that struct in order to avoid those warnings but tests should pass just fine and it shouldn't impact anything.

**Comment by ddelnano** [comment]
Sorry that was a horrible description.  I will post a much more detailed explanation today now that I am back from my trip.  Correct me if I am wrong but those should just be warnings and have no impact on the test results.

**Comment by bradobro** [comment]
Thanks ddelnano. When you get settled, I'd be glad to PR a fix if you can describe a strategy. Is it possible to provide stub methods that do match the signatures, or are you thinking something else?

**Comment by ddelnano** [comment]
If you read the documentation under the Overview section [here](https://golang.org/pkg/net/rpc/) you will see that methods to be used over RPC must match a very specific signature.  Now if you look at the struct that has its methods exported for use over RPC you will see that half of the methods match the signature specified in the docs [here](https://github.com/snikch/goodman/blob/master/hooks/hooks.go#L38-L101).  The other [half](https://github.com/snikch/goodman/blob/master/hooks/hooks.go#L103-L150) _are not_ used for RPC, however, when exporting a struct over RPC go will check all methods of the struct.  So the warning is happening because some of the methods do not match the signature even tho they are not being used via RPC.

I believe the best way to fix this is to split out the non conforming methods of the struct to a different struct and to separate the responsibilities.  Then all the methods of the struct used for RPC would fit the criteria.

So the hooks that aren't implemented **are** being ignored (as in they are not executing) but when the struct is registered via RPC all methods that don't match throw that warning.

The reason why I did not fix this before is because functionally the code still behaves correctly despite the warnings.  I was planning on fixing these warnings at some point but didn't have a time table yet.  If you want to make a fix for this I would greatly appreciate that.

Edit: Added another paragraph for clarity
